/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as ReunioesRouteImport } from './routes/reunioes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DemandasRouteImport } from './routes/demandas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdminUsuariosRouteImport } from './routes/api.admin.usuarios'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunioesRoute = ReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandasRoute = DemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsuariosRoute = ApiAdminUsuariosRouteImport.update({
  id: '/api/admin/usuarios',
  path: '/api/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/atividades': typeof AtividadesRoute
  '/avisos': typeof AvisosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/demandas': typeof DemandasRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/portfolio': typeof PortfolioRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRoute
  '/tarefas': typeof TarefasRoute
  '/api/admin/usuarios': typeof ApiAdminUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/atividades': typeof AtividadesRoute
  '/avisos': typeof AvisosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/demandas': typeof DemandasRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/portfolio': typeof PortfolioRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRoute
  '/tarefas': typeof TarefasRoute
  '/api/admin/usuarios': typeof ApiAdminUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/atividades': typeof AtividadesRoute
  '/avisos': typeof AvisosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/demandas': typeof DemandasRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/portfolio': typeof PortfolioRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRoute
  '/tarefas': typeof TarefasRoute
  '/api/admin/usuarios': typeof ApiAdminUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alterar-senha'
    | '/atividades'
    | '/avisos'
    | '/configuracoes'
    | '/demandas'
    | '/equipe'
    | '/login'
    | '/perfil'
    | '/portfolio'
    | '/relatorios'
    | '/reunioes'
    | '/tarefas'
    | '/api/admin/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha'
    | '/atividades'
    | '/avisos'
    | '/configuracoes'
    | '/demandas'
    | '/equipe'
    | '/login'
    | '/perfil'
    | '/portfolio'
    | '/relatorios'
    | '/reunioes'
    | '/tarefas'
    | '/api/admin/usuarios'
  id:
    | '__root__'
    | '/'
    | '/alterar-senha'
    | '/atividades'
    | '/avisos'
    | '/configuracoes'
    | '/demandas'
    | '/equipe'
    | '/login'
    | '/perfil'
    | '/portfolio'
    | '/relatorios'
    | '/reunioes'
    | '/tarefas'
    | '/api/admin/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  AtividadesRoute: typeof AtividadesRoute
  AvisosRoute: typeof AvisosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DemandasRoute: typeof DemandasRoute
  EquipeRoute: typeof EquipeRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PortfolioRoute: typeof PortfolioRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ReunioesRoute: typeof ReunioesRoute
  TarefasRoute: typeof TarefasRoute
  ApiAdminUsuariosRoute: typeof ApiAdminUsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunioes': {
      id: '/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof ReunioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandas': {
      id: '/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof DemandasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/usuarios': {
      id: '/api/admin/usuarios'
      path: '/api/admin/usuarios'
      fullPath: '/api/admin/usuarios'
      preLoaderRoute: typeof ApiAdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlterarSenhaRoute: AlterarSenhaRoute,
  AtividadesRoute: AtividadesRoute,
  AvisosRoute: AvisosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DemandasRoute: DemandasRoute,
  EquipeRoute: EquipeRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PortfolioRoute: PortfolioRoute,
  RelatoriosRoute: RelatoriosRoute,
  ReunioesRoute: ReunioesRoute,
  TarefasRoute: TarefasRoute,
  ApiAdminUsuariosRoute: ApiAdminUsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
