/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as ReunioesRouteImport } from './routes/reunioes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DemandasRouteImport } from './routes/demandas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiAdminUsuariosRouteImport } from './routes/api.admin.usuarios'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunioesRoute = ReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandasRoute = DemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsuariosRoute = ApiAdminUsuariosRouteImport.update({
  id: '/api/admin/usuarios',
  path: '/api/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/atividades': typeof AtividadesRoute
  '/avisos': typeof AvisosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/demandas': typeof DemandasRoute
  '/equipe': typeof EquipeRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/perfil': typeof PerfilRoute
  '/portfolio': typeof PortfolioRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRoute
  '/tarefas': typeof TarefasRoute
  '/unidades': typeof UnidadesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/admin/usuarios': typeof ApiAdminUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/atividades': typeof AtividadesRoute
  '/avisos': typeof AvisosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/demandas': typeof DemandasRoute
  '/equipe': typeof EquipeRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/perfil': typeof PerfilRoute
  '/portfolio': typeof PortfolioRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRoute
  '/tarefas': typeof TarefasRoute
  '/unidades': typeof UnidadesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/admin/usuarios': typeof ApiAdminUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/atividades': typeof AtividadesRoute
  '/avisos': typeof AvisosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/demandas': typeof DemandasRoute
  '/equipe': typeof EquipeRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/perfil': typeof PerfilRoute
  '/portfolio': typeof PortfolioRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRoute
  '/tarefas': typeof TarefasRoute
  '/unidades': typeof UnidadesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/admin/usuarios': typeof ApiAdminUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alterar-senha'
    | '/atividades'
    | '/avisos'
    | '/configuracoes'
    | '/demandas'
    | '/equipe'
    | '/insights'
    | '/login'
    | '/mcp'
    | '/perfil'
    | '/portfolio'
    | '/relatorios'
    | '/reunioes'
    | '/tarefas'
    | '/unidades'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/admin/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha'
    | '/atividades'
    | '/avisos'
    | '/configuracoes'
    | '/demandas'
    | '/equipe'
    | '/insights'
    | '/login'
    | '/mcp'
    | '/perfil'
    | '/portfolio'
    | '/relatorios'
    | '/reunioes'
    | '/tarefas'
    | '/unidades'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/admin/usuarios'
  id:
    | '__root__'
    | '/'
    | '/alterar-senha'
    | '/atividades'
    | '/avisos'
    | '/configuracoes'
    | '/demandas'
    | '/equipe'
    | '/insights'
    | '/login'
    | '/mcp'
    | '/perfil'
    | '/portfolio'
    | '/relatorios'
    | '/reunioes'
    | '/tarefas'
    | '/unidades'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/admin/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  AtividadesRoute: typeof AtividadesRoute
  AvisosRoute: typeof AvisosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DemandasRoute: typeof DemandasRoute
  EquipeRoute: typeof EquipeRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PerfilRoute: typeof PerfilRoute
  PortfolioRoute: typeof PortfolioRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ReunioesRoute: typeof ReunioesRoute
  TarefasRoute: typeof TarefasRoute
  UnidadesRoute: typeof UnidadesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAdminUsuariosRoute: typeof ApiAdminUsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunioes': {
      id: '/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof ReunioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandas': {
      id: '/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof DemandasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/usuarios': {
      id: '/api/admin/usuarios'
      path: '/api/admin/usuarios'
      fullPath: '/api/admin/usuarios'
      preLoaderRoute: typeof ApiAdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlterarSenhaRoute: AlterarSenhaRoute,
  AtividadesRoute: AtividadesRoute,
  AvisosRoute: AvisosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DemandasRoute: DemandasRoute,
  EquipeRoute: EquipeRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PerfilRoute: PerfilRoute,
  PortfolioRoute: PortfolioRoute,
  RelatoriosRoute: RelatoriosRoute,
  ReunioesRoute: ReunioesRoute,
  TarefasRoute: TarefasRoute,
  UnidadesRoute: UnidadesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAdminUsuariosRoute: ApiAdminUsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
